#ifndef _PAGING_H_
#define _PAGING_H_

#define FRAMES_COUNT      (128 * 1024)
#define FRAME_SIZE        4096
#define FRAMES_START_ADDR 0x100000

#define PAGE_DIRECTORY_START_ADDR 0
#define PAGE_TABLES_START_ADDR    1
#define PAGE_TABLE_COUNT       1024
#define USER_PAGES_START_ADDR (PAGE_DIRECTORY_START_ADDR + PAGE_TABLE_COUNT)

#define KERNEL_START_ADDR  0x6400000
#define KERNEL_SOURCE_SIZE 256 // 256 * 4096 = 1MB
#define KERNEL_STACK_START_ADDR (KERNEL_START_ADDR + 0x100000 + FRAME_SIZE) // kernel + 1MB + 1KB
#define KERNEL_STACK_SIZE 4

void init_pagining();

#endif